source 'https://github.com/CocoaPods/Specs.git'

target 'KocomojoKit', :exclusive => true do
  pod "KocomojoKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "KocomojoKit", :path => "../"

  
end
